import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>sdfsdf</header>
      <main className={styles.main}>sdasd</main>
      <footer className={styles.footer}>sdfsdf</footer>
    </div>
  )
}

export default Home
